did some stuff to post and delete for scholarship
I am getting a weird problem that I might need help with. Whenever I use the commented out arguments for post in scholarship, I receive "TypeError: missing 10 required positional arguments" and I'm not sure how to fix this.